### ISSUE TITLE
Thevideo URL Resolution requires a dependency update

### ISSUE THREAD

**Issue by HalosGhost** [cthlo/exoduscli#2]
According to [tvaddons](https://www.tvaddons.ag/rickroll-thevideo/), an update to URL resolver needs to be included.

**Comment by cthlo** [comment]
Disabled TheVideo resolver: 129da55

**Comment by HalosGhost** [comment]
@cthlo, Oh, that's too bad; I was hoping the resolver could be updated so that it could still be used. It is one of the more reliable ones.

**Comment by cthlo** [comment]
Ah, actually, Exodus is blocking thevideo.me sources since 2.0.7. I'll enable it again if they're bringing it back.
